version: "3.1"

services:
  watchtower:
    build:
      context: ./images
      dockerfile: watchtower.dockerfile
    image: hiramlabs/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    network_mode: "host"

  portainer:
    build:
      context: ./images
      dockerfile: portainer.dockerfile
    image: hiramlabs/portainer
    container_name: portainer
    restart: unless-stopped
    #    ports:
    #      - 9020:9000
    #      - 9021:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - interface

  registry:
    build:
      context: ./images
      dockerfile: registry.dockerfile
    image: hiramlabs/registry
    container_name: registry
    restart: unless-stopped
    #    ports:
    #      - 9022:5000
    volumes:
      - ./volume/registry:/auth
      - registry_data:/var/lib/registry
    networks:
      - interface

  registryui:
    build:
      context: ./images
      dockerfile: registryui.dockerfile
    image: hiramlabs/registryui
    container_name: registryui
    restart: unless-stopped
    #    ports:
    #      - 9023:80
    depends_on:
      - registry
    networks:
      - interface

  cdn:
    build:
      context: ./images
      dockerfile: cdn.dockerfile
    image: hiramlabs/cdn
    container_name: cdn
    restart: unless-stopped
    #    ports:
    #      - 9024:80
    volumes:
      - ~/cdn:/srv
    networks:
      - interface

volumes:
  portainer_data:
  registry_data:

networks:
  interface:
    external:
      name: interface
