version: "3.1"

services:
  portainer:
    build:
      context: ./images
      dockerfile: portainer.dockerfile
    image: hiramlabs/portainer
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9020:9000
      - 9021:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
