#!/bin/bash

__ARG=$1

__START_DOCKER_COMPOSE="start"
__STOP_DOCKER_COMPOSE="stop"

__START_CDN_SHELL="cdn:shell"

if [[ "$__ARG" == "$__START_DOCKER_COMPOSE" ]]; then
    shift
    docker-compose up -d "$@"
fi

if [[ "$__ARG" == "$__STOP_DOCKER_COMPOSE" ]]; then
    shift
    docker-compose down "$@"
fi

if [[ "$__ARG" == "$__START_CDN_SHELL" ]]; then
    docker exec -it cdn /bin/bash --login
fi
