FROM joxit/docker-registry-ui:latest

<<<<<<< Updated upstream
ENV ENV_DOCKER_REGISTRY_HOST registry
ENV ENV_DOCKER_REGISTRY_PORT 5000
ENV ENV_REGISTRY_PROXY_FQDN registry.hiramlabs.com/v2
ENV ENV_REGISTRY_PROXY_PORT 443
ENV ENV_MODE_BROWSE_ONLY false
||||||| merged common ancestors
ENV ENV_DOCKER_REGISTRY_HOST registry
ENV ENV_DOCKER_REGISTRY_PORT 5000
ENV ENV_REGISTRY_PROXY_FQDN registry.hiramlabs.com
ENV ENV_REGISTRY_PROXY_PORT 443
ENV ENV_MODE_BROWSE_ONLY false
=======
ENV REGISTRY_TITLE HL-Registry
ENV REGISTRY_URL registry:5000
ENV SINGLE_REGISTRY true
ENV DELETE_IMAGES true
>>>>>>> Stashed changes
